title: Anıl Elakaş Teknoloji
description: > # this means to ignore newlines until "baseurl:"
  Teknoloji ve yazılım üzerine yazılarımı paylaştığım blogum.
  Yazılım geliştirme, back-end ve front-end teknolojileri, Kotlin, JavaScript, React ve daha fazlası.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anilelakas.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Anıl Elakaş # add your name
author-img: anil-elakas.jpg # add your photo
about-author: I am a software developer focusing on back-end development, front-end development and data science. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: anilelakas # add your Github handle
social-linkedin: anilelakas # add your Linkedin handle
social-email: anilelakas@hotmail.com.tr # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
